#!/bin/bash
ScriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FortranDepCore="$ScriptDir/FortranDepCore.x"
if [ ! -x "$FortranDepCore" ]; then
	echo "Error: FortranDepCore.x not found. Must be in same directory as FortranDep." >&2
	exit 1
fi

Usage() {
	echo "Generates make-compatible dependency rules for Fortran source files." >&2
	echo "Usage: "$0" [-p] [-d] [-l] <file> [GccArgs]" >&2
	echo "  -p: Add phony targets for each #include dependency." >&2
	echo "  -d: Add a dependency target for the source file (depends on the source and all included files)." >&2
	echo "  -l: Enable lax mode (object files depend on program units defined within them)." >&2
	echo "  GccArgs: list of arguments to pass to gcc. Applied when preprocessing." >&2
	exit 1
}

MergeIncludes() {
	local MakeRule="$1"
	local AdditionalIncludes="$2"

	printf "%s\n" "$MakeRule" | awk -v add="$AdditionalIncludes" '
    BEGIN {
      n = split(add, extra, "\n")
      count = 0
      for (i = 1; i <= n; i++) {
        if (extra[i] != "") count++
      }
    }

    /\\$/ {
      print
      next
    }

    {
      if (count == 0) {
        print
      } else {
        printf "%s  \\\n", $0

        c = 0
        for (i = 1; i <= n; i++) {
          if (extra[i] != "") {
            c++
            if (c < count) {
              printf "  %s  \\\n", extra[i]
            } else {
              printf "  %s\n", extra[i]
            }
          }
        }
      }
  }'
}

PhonyIncs=false
DepTarget=false
Lax=false

while getopts ":pdl" opt; do
	case $opt in
	p) PhonyIncs=true ;;
	d) DepTarget=true ;;
	l) Lax=true ;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		Usage
		;;
	esac
done

shift $((OPTIND - 1))

File="$1"
shift 1

if [ -z "$File" ]; then
	Usage
fi

Basename=$(echo "$File" | sed "s|.*/||" | sed "s|\(.*\)\..*|\1|")

####################################
# CPP part.

# Preprocessed output and line count.
PreprocessedOutput="$(gcc "$@" -E -cpp -I. "$File")"
if [ $? -ne 0 ]; then
	exit 1
fi
PreprocessedOutputLC="$(echo "$PreprocessedOutput" | wc -l)"

# Make include rules with dummys.
IncludeRulesMP="$(gcc "$@" -E -cpp -I. -MM -MP "$File")"
if [ $? -ne 0 ]; then
	exit 1
fi
IncludeRulesMP="$(echo "${IncludeRulesMP}" | awk "NR>"$PreprocessedOutputLC"")"

# Make include rules without dummys and line count up to dummys.
IncludeRules="$(gcc "$@" -E -cpp -I. -MM "$File")"
if [ $? -ne 0 ]; then
	exit 1
fi
IncludeRules="$(echo "${IncludeRules}" | awk "NR>"$PreprocessedOutputLC"")"
LCUpToIncludeRules="$(echo "$IncludeRules" | wc -l)"

# Dummy list ':'-separated.
DummyList="$(echo "${IncludeRulesMP}" | awk "NR>"$LCUpToIncludeRules"")"
# Dummy list.
IncludeFiles="$(echo "${DummyList}" | sed "s|:||g")"

####################################
# Fortran part.

# Get Fortran dependencies.
if [ "$Lax" = true ]; then
	FortranDeps=$(eval "$FortranDepCore -l" <<<"$PreprocessedOutput")
else
	FortranDeps=$(eval "$FortranDepCore" <<<"$PreprocessedOutput")
fi
if [ $? -ne 0 ]; then
	exit 1
fi

if [ "$DepTarget" = true ]; then
	FortranDeps="${Basename}.d:  $File
${FortranDeps}"
fi

# Merge with #include dependencies.
FortranDeps="$(MergeIncludes "$FortranDeps" "$IncludeFiles")"

# Replace placeholder names.
FortranDeps=$(echo "${FortranDeps}" |
	sed "s|#OBJECT#|$Basename.o|g" |
	sed "s|#SOURCEFILE#|$File|g")

# Print rules.
echo "${FortranDeps}"

####################################
if [ "$PhonyIncs" = true ]; then
	if [[ $DummyList =~ [^[:space:]] ]]; then
		printf '%s\n' "$DummyList"
	fi
fi
